chore: add homework 6
Otus-DevOps-2019-08/Vendin_infra pull request #3
Opened 2019-10-20 12:01 UTC by Vendin

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [x] Задание со *: создание startup_script.sh

## В процессе сделано:
 - Bash скрипты для развертывания Ruby, MongoDB и тестового приложение
 - Создание бакета в котором хранится startup_script.sh, который испольузется при старте новой VM

## Как проверить работоспособность:
 - Перейти по ссылке http://35.204.119.206:9292/

## PR checklist
 - [*] Выставил cloud-testapp label

2019-10-23 05:36 UTC, mrgreyves requested changes
Здравствуйте!) Вам нужно перепроверить свой репозитирой. Нужно что бы скрипты были исполняемыми, так же проверьте есть ли пустые строки в конце файлов.

2019-10-31 17:37 UTC, mrgreyves requested changes
Оставил комментарий к файлам =)

2019-10-31 17:37 UTC, mrgreyves commented on install_mongodb.sh
> +sudo bash -c 'echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list'
Вот тут ошибочка =)

2019-10-31 17:37 UTC, mrgreyves commented on install_mongodb.sh
> +sudo bash -c 'echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list'
Именно в третьей строке =)

2019-11-02 11:48 UTC, Vendin commented on install_mongodb.sh
> +sudo bash -c 'echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list'
Вот это да :smiley: :laughing: :stuck_out_tongue_closed_eyes:

2019-11-03 10:17 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. Все хорошо, дз принимаю!=)

2019-11-03 10:23 UTC, merged